vich_uploader:
    db_driver: orm        # or mongodb or phpcr - default db driver
    twig: true            # set to false to disable twig integration
    form: true            # set to false to disable form integration
    storage: file_system  # or gaufrette or flysystem
    metadata:
        auto_detection: true
        cache: file
        type: attribute    # or annotation
    mappings:
      documents_pdf: 
        uri_prefix: /documents
        upload_destination: '%kernel.project_dir%/public/documents/properties/tf'
        namer: Vich\UploaderBundle\Naming\UniqidNamer
      user_picture:
        uri_prefix: /users
        upload_destination: '%kernel.project_dir%/public/pictures/user'
        namer:
          service: Vich\UploaderBundle\Naming\PropertyNamer
          options: { property: 'username' }
    #mappings:
    #  products:
    #        uri_prefix: /images/products
    #        upload_destination: '%kernel.project_dir%/public/images/products'
