<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerXY4GPxl\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerXY4GPxl/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerXY4GPxl.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerXY4GPxl\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerXY4GPxl\App_KernelDevDebugContainer([
    'container.build_hash' => 'XY4GPxl',
    'container.build_id' => '16c84207',
    'container.build_time' => 1719744873,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerXY4GPxl');
