<?php

// This file has been auto-generated by the Symfony Cache Component.

return [[

'_default' => 0,

], [

0 => [
    'entrypoints' => [
        'login' => [
            'js' => [
                '/build/runtime.0d883029.js',
                '/build/37.aac2040e.js',
                '/build/845.7a2ed71b.js',
                '/build/login.1f6b603e.js',
            ],
            'css' => [
                '/build/login.573f928a.css',
            ],
        ],
        'dashboard' => [
            'js' => [
                '/build/runtime.0d883029.js',
                '/build/37.aac2040e.js',
                '/build/419.d254f84a.js',
                '/build/dashboard.5c97f3e7.js',
            ],
            'css' => [
                '/build/419.254e9280.css',
                '/build/dashboard.7f611b22.css',
            ],
        ],
        'consultation' => [
            'js' => [
                '/build/runtime.0d883029.js',
                '/build/37.aac2040e.js',
                '/build/590.fa97c72e.js',
                '/build/consultation.63e8f0eb.js',
            ],
            'css' => [
                '/build/consultation.28c6fb6f.css',
            ],
        ],
    ],
],

]];
