<?php

namespace ContainerXY4GPxl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RvRYz5qService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.RvRYz5q' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.RvRYz5q'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Affectation' => ['privates', '.errored..service_locator.RvRYz5q.App\\Entity\\Affectations', NULL, 'Cannot autowire service ".service_locator.RvRYz5q": it needs an instance of "App\\Entity\\Affectations" but this type has been excluded in "config/services.yaml".'],
            'AffectationsRepository' => ['privates', 'App\\Repository\\AffectationsRepository', 'getAffectationsRepositoryService', true],
        ], [
            'Affectation' => 'App\\Entity\\Affectations',
            'AffectationsRepository' => 'App\\Repository\\AffectationsRepository',
        ]);
    }
}
