<?php

namespace ContainerXY4GPxl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NWoUxjQService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.nWoUxjQ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.nWoUxjQ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'division' => ['privates', '.errored..service_locator.nWoUxjQ.App\\Entity\\Divisions', NULL, 'Cannot autowire service ".service_locator.nWoUxjQ": it needs an instance of "App\\Entity\\Divisions" but this type has been excluded in "config/services.yaml".'],
            'divisionsRepository' => ['privates', 'App\\Repository\\DivisionsRepository', 'getDivisionsRepositoryService', true],
        ], [
            'division' => 'App\\Entity\\Divisions',
            'divisionsRepository' => 'App\\Repository\\DivisionsRepository',
        ]);
    }
}
