<?php

namespace ContainerXY4GPxl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_5I6AnDmService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.5I6AnDm' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.5I6AnDm'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'directionsRepository' => ['privates', 'App\\Repository\\DirectionsRepository', 'getDirectionsRepositoryService', true],
            'divisionsRepository' => ['privates', 'App\\Repository\\DivisionsRepository', 'getDivisionsRepositoryService', true],
            'postesRepository' => ['privates', 'App\\Repository\\PostesRepository', 'getPostesRepositoryService', true],
            'secretariatsRepository' => ['privates', 'App\\Repository\\SecretariatsRepository', 'getSecretariatsRepositoryService', true],
            'servicesRepository' => ['privates', 'App\\Repository\\ServicesRepository', 'getServicesRepositoryService', true],
            'user' => ['privates', '.errored..service_locator.5I6AnDm.App\\Entity\\Users', NULL, 'Cannot autowire service ".service_locator.5I6AnDm": it needs an instance of "App\\Entity\\Users" but this type has been excluded in "config/services.yaml".'],
        ], [
            'directionsRepository' => 'App\\Repository\\DirectionsRepository',
            'divisionsRepository' => 'App\\Repository\\DivisionsRepository',
            'postesRepository' => 'App\\Repository\\PostesRepository',
            'secretariatsRepository' => 'App\\Repository\\SecretariatsRepository',
            'servicesRepository' => 'App\\Repository\\ServicesRepository',
            'user' => 'App\\Entity\\Users',
        ]);
    }
}
