<?php

namespace ContainerXY4GPxl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_C7CRww0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.C7CRww0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.C7CRww0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'typeDocument' => ['privates', '.errored..service_locator.C7CRww0.App\\Entity\\TypeDocuments', NULL, 'Cannot autowire service ".service_locator.C7CRww0": it needs an instance of "App\\Entity\\TypeDocuments" but this type has been excluded in "config/services.yaml".'],
            'typeDocumentsRepository' => ['privates', 'App\\Repository\\TypeDocumentsRepository', 'getTypeDocumentsRepositoryService', true],
        ], [
            'typeDocument' => 'App\\Entity\\TypeDocuments',
            'typeDocumentsRepository' => 'App\\Repository\\TypeDocumentsRepository',
        ]);
    }
}
