<?php

namespace ContainerXY4GPxl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F7C2SsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.F7C_2Ss' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.F7C_2Ss'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'divisionsRepository' => ['privates', 'App\\Repository\\DivisionsRepository', 'getDivisionsRepositoryService', true],
            'service' => ['privates', '.errored..service_locator.F7C_2Ss.App\\Entity\\Services', NULL, 'Cannot autowire service ".service_locator.F7C_2Ss": it needs an instance of "App\\Entity\\Services" but this type has been excluded in "config/services.yaml".'],
            'servicesRepository' => ['privates', 'App\\Repository\\ServicesRepository', 'getServicesRepositoryService', true],
        ], [
            'divisionsRepository' => 'App\\Repository\\DivisionsRepository',
            'service' => 'App\\Entity\\Services',
            'servicesRepository' => 'App\\Repository\\ServicesRepository',
        ]);
    }
}
