<?php

namespace ContainerXY4GPxl;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecretariatsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.T8QqxDI.App\Entity\Secretariats' shared service.
     *
     * @return \App\Entity\Secretariats
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.T8QqxDI": it needs an instance of "App\\Entity\\Secretariats" but this type has been excluded in "config/services.yaml".');
    }
}
