<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Postes extends \App\Entity\Postes implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'Niveau', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'Fonction', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'Agent', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'Owner', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'DateDeb', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'Poste_At', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'DateFin', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'Type', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'documents', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'affectations'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'Niveau', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'Fonction', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'Agent', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'Owner', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'DateDeb', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'Poste_At', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'DateFin', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'Type', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'documents', '' . "\0" . 'App\\Entity\\Postes' . "\0" . 'affectations'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Postes $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveau(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveau', []);

        return parent::getNiveau();
    }

    /**
     * {@inheritDoc}
     */
    public function setNiveau(string $Niveau): \App\Entity\Postes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiveau', [$Niveau]);

        return parent::setNiveau($Niveau);
    }

    /**
     * {@inheritDoc}
     */
    public function getFonction(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getFonction', []);

        return parent::getFonction();
    }

    /**
     * {@inheritDoc}
     */
    public function setFonction(string $Fonction): \App\Entity\Postes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setFonction', [$Fonction]);

        return parent::setFonction($Fonction);
    }

    /**
     * {@inheritDoc}
     */
    public function getAgent(): ?\App\Entity\Users
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAgent', []);

        return parent::getAgent();
    }

    /**
     * {@inheritDoc}
     */
    public function setAgent(?\App\Entity\Users $Agent): \App\Entity\Postes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setAgent', [$Agent]);

        return parent::setAgent($Agent);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwner(): ?\App\Entity\Users
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwner', []);

        return parent::getOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwner(?\App\Entity\Users $Owner): \App\Entity\Postes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwner', [$Owner]);

        return parent::setOwner($Owner);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDeb(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDeb', []);

        return parent::getDateDeb();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDeb(\DateTimeInterface $DateDeb): \App\Entity\Postes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDeb', [$DateDeb]);

        return parent::setDateDeb($DateDeb);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFin(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFin', []);

        return parent::getDateFin();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFin(?\DateTimeInterface $DateFin): \App\Entity\Postes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFin', [$DateFin]);

        return parent::setDateFin($DateFin);
    }

    /**
     * {@inheritDoc}
     */
    public function isStatus(): ?bool
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'isStatus', []);

        return parent::isStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus(bool $status): \App\Entity\Postes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoste_At(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoste_At', []);

        return parent::getPoste_At();
    }

    /**
     * {@inheritDoc}
     */
    public function getType(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getType', []);

        return parent::getType();
    }

    /**
     * {@inheritDoc}
     */
    public function setType(?string $Type): \App\Entity\Postes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setType', [$Type]);

        return parent::setType($Type);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocuments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocuments', []);

        return parent::getDocuments();
    }

    /**
     * {@inheritDoc}
     */
    public function addDocument(\App\Entity\Documents $document): \App\Entity\Postes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDocument', [$document]);

        return parent::addDocument($document);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDocument(\App\Entity\Documents $document): \App\Entity\Postes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDocument', [$document]);

        return parent::removeDocument($document);
    }

    /**
     * {@inheritDoc}
     */
    public function getAffectations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAffectations', []);

        return parent::getAffectations();
    }

    /**
     * {@inheritDoc}
     */
    public function addAffectation(\App\Entity\Affectations $affectation): \App\Entity\Postes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAffectation', [$affectation]);

        return parent::addAffectation($affectation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAffectation(\App\Entity\Affectations $affectation): \App\Entity\Postes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAffectation', [$affectation]);

        return parent::removeAffectation($affectation);
    }

}
