<?php

namespace Proxies\__CG__\App\Entity;


/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Documents extends \App\Entity\Documents implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Objet', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Chemin', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Mouvement', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Document_at', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Owner', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'TypeDocument', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Structure', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Reference', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'NumeroEnregistrement', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Poste', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Niveau', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'DateArrivee', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'DateDocument', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'provenances', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Affectations', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Reponse', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'documents', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Initiateur', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Observation', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'PosteOwner'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'id', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Objet', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Chemin', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Mouvement', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Document_at', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Owner', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'TypeDocument', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'status', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Structure', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Reference', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'NumeroEnregistrement', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Poste', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Niveau', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'DateArrivee', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'DateDocument', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'provenances', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Affectations', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Reponse', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'documents', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Initiateur', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'Observation', '' . "\0" . 'App\\Entity\\Documents' . "\0" . 'PosteOwner'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Documents $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load(): void
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized(): bool
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized): void
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null): void
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer(): ?\Closure
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null): void
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner(): ?\Closure
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties(): array
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getObjet(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObjet', []);

        return parent::getObjet();
    }

    /**
     * {@inheritDoc}
     */
    public function setObjet(string $Objet): \App\Entity\Documents
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObjet', [$Objet]);

        return parent::setObjet($Objet);
    }

    /**
     * {@inheritDoc}
     */
    public function getMouvement(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getMouvement', []);

        return parent::getMouvement();
    }

    /**
     * {@inheritDoc}
     */
    public function setMouvement(string $Mouvement): \App\Entity\Documents
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setMouvement', [$Mouvement]);

        return parent::setMouvement($Mouvement);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocumentAt(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocumentAt', []);

        return parent::getDocumentAt();
    }

    /**
     * {@inheritDoc}
     */
    public function setDocumentAt(\DateTimeInterface $Document_at): \App\Entity\Documents
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDocumentAt', [$Document_at]);

        return parent::setDocumentAt($Document_at);
    }

    /**
     * {@inheritDoc}
     */
    public function getOwner(): ?\App\Entity\Users
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getOwner', []);

        return parent::getOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setOwner(?\App\Entity\Users $Owner): \App\Entity\Documents
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setOwner', [$Owner]);

        return parent::setOwner($Owner);
    }

    /**
     * {@inheritDoc}
     */
    public function getTypeDocument(): ?\App\Entity\TypeDocuments
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTypeDocument', []);

        return parent::getTypeDocument();
    }

    /**
     * {@inheritDoc}
     */
    public function setTypeDocument(?\App\Entity\TypeDocuments $TypeDocument): \App\Entity\Documents
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTypeDocument', [$TypeDocument]);

        return parent::setTypeDocument($TypeDocument);
    }

    /**
     * {@inheritDoc}
     */
    public function getStatus()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStatus', []);

        return parent::getStatus();
    }

    /**
     * {@inheritDoc}
     */
    public function setStatus($status)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStatus', [$status]);

        return parent::setStatus($status);
    }

    /**
     * {@inheritDoc}
     */
    public function getChemin()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getChemin', []);

        return parent::getChemin();
    }

    /**
     * {@inheritDoc}
     */
    public function setChemin($Chemin)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setChemin', [$Chemin]);

        return parent::setChemin($Chemin);
    }

    /**
     * {@inheritDoc}
     */
    public function getProvenances(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getProvenances', []);

        return parent::getProvenances();
    }

    /**
     * {@inheritDoc}
     */
    public function addProvenance(\App\Entity\Provenances $provenance): \App\Entity\Documents
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addProvenance', [$provenance]);

        return parent::addProvenance($provenance);
    }

    /**
     * {@inheritDoc}
     */
    public function removeProvenance(\App\Entity\Provenances $provenance): \App\Entity\Documents
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeProvenance', [$provenance]);

        return parent::removeProvenance($provenance);
    }

    /**
     * {@inheritDoc}
     */
    public function getAffectations(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getAffectations', []);

        return parent::getAffectations();
    }

    /**
     * {@inheritDoc}
     */
    public function addAffectation(\App\Entity\Affectations $Affectation): \App\Entity\Documents
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addAffectation', [$Affectation]);

        return parent::addAffectation($Affectation);
    }

    /**
     * {@inheritDoc}
     */
    public function removeAffectation(\App\Entity\Affectations $Affectation): \App\Entity\Documents
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeAffectation', [$Affectation]);

        return parent::removeAffectation($Affectation);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateArrivee()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateArrivee', []);

        return parent::getDateArrivee();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateArrivee($DateArrivee)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateArrivee', [$DateArrivee]);

        return parent::setDateArrivee($DateArrivee);
    }

    /**
     * {@inheritDoc}
     */
    public function getReference()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReference', []);

        return parent::getReference();
    }

    /**
     * {@inheritDoc}
     */
    public function setReference($Reference)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReference', [$Reference]);

        return parent::setReference($Reference);
    }

    /**
     * {@inheritDoc}
     */
    public function getStructure()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getStructure', []);

        return parent::getStructure();
    }

    /**
     * {@inheritDoc}
     */
    public function setStructure($Structure)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setStructure', [$Structure]);

        return parent::setStructure($Structure);
    }

    /**
     * {@inheritDoc}
     */
    public function getNumeroEnregistrement(): ?int
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNumeroEnregistrement', []);

        return parent::getNumeroEnregistrement();
    }

    /**
     * {@inheritDoc}
     */
    public function setNumeroEnregistrement(?int $NumeroEnregistrement)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNumeroEnregistrement', [$NumeroEnregistrement]);

        return parent::setNumeroEnregistrement($NumeroEnregistrement);
    }

    /**
     * {@inheritDoc}
     */
    public function __toString(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, '__toString', []);

        return parent::__toString();
    }

    /**
     * {@inheritDoc}
     */
    public function getReponse(): ?\App\Entity\Documents
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getReponse', []);

        return parent::getReponse();
    }

    /**
     * {@inheritDoc}
     */
    public function setReponse(?\App\Entity\Documents $Reponse): \App\Entity\Documents
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setReponse', [$Reponse]);

        return parent::setReponse($Reponse);
    }

    /**
     * {@inheritDoc}
     */
    public function getDocuments(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDocuments', []);

        return parent::getDocuments();
    }

    /**
     * {@inheritDoc}
     */
    public function addDocument(\App\Entity\Documents $document): \App\Entity\Documents
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addDocument', [$document]);

        return parent::addDocument($document);
    }

    /**
     * {@inheritDoc}
     */
    public function removeDocument(\App\Entity\Documents $document): \App\Entity\Documents
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeDocument', [$document]);

        return parent::removeDocument($document);
    }

    /**
     * {@inheritDoc}
     */
    public function getPoste(): string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPoste', []);

        return parent::getPoste();
    }

    /**
     * {@inheritDoc}
     */
    public function setPoste(string $Poste): \App\Entity\Documents
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPoste', [$Poste]);

        return parent::setPoste($Poste);
    }

    /**
     * {@inheritDoc}
     */
    public function getNiveau()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNiveau', []);

        return parent::getNiveau();
    }

    /**
     * {@inheritDoc}
     */
    public function setNiveau($Niveau)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNiveau', [$Niveau]);

        return parent::setNiveau($Niveau);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDocument()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDocument', []);

        return parent::getDateDocument();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDocument($DateDocument)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDocument', [$DateDocument]);

        return parent::setDateDocument($DateDocument);
    }

    /**
     * {@inheritDoc}
     */
    public function getInitiateur(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getInitiateur', []);

        return parent::getInitiateur();
    }

    /**
     * {@inheritDoc}
     */
    public function setInitiateur(?string $Initiateur): \App\Entity\Documents
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setInitiateur', [$Initiateur]);

        return parent::setInitiateur($Initiateur);
    }

    /**
     * {@inheritDoc}
     */
    public function getObservation(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getObservation', []);

        return parent::getObservation();
    }

    /**
     * {@inheritDoc}
     */
    public function setObservation(?string $Observation): \App\Entity\Documents
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setObservation', [$Observation]);

        return parent::setObservation($Observation);
    }

    /**
     * {@inheritDoc}
     */
    public function getPosteOwner(): ?\App\Entity\Postes
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getPosteOwner', []);

        return parent::getPosteOwner();
    }

    /**
     * {@inheritDoc}
     */
    public function setPosteOwner(?\App\Entity\Postes $PosteOwner): \App\Entity\Documents
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setPosteOwner', [$PosteOwner]);

        return parent::setPosteOwner($PosteOwner);
    }

}
