<?php

namespace ContainerWVTsjGy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Q1I7dsvService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Q1I7dsv' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Q1I7dsv'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Affectation' => ['privates', '.errored..service_locator.Q1I7dsv.App\\Entity\\Affectations', NULL, 'Cannot autowire service ".service_locator.Q1I7dsv": it needs an instance of "App\\Entity\\Affectations" but this type has been excluded in "config/services.yaml".'],
            'affectationsRepository' => ['privates', 'App\\Repository\\AffectationsRepository', 'getAffectationsRepositoryService', true],
        ], [
            'Affectation' => 'App\\Entity\\Affectations',
            'affectationsRepository' => 'App\\Repository\\AffectationsRepository',
        ]);
    }
}
