<?php

namespace ContainerWVTsjGy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_AjO6koBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.AjO6koB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.AjO6koB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'Affectation' => ['privates', '.errored..service_locator.AjO6koB.App\\Entity\\Affectations', NULL, 'Cannot autowire service ".service_locator.AjO6koB": it needs an instance of "App\\Entity\\Affectations" but this type has been excluded in "config/services.yaml".'],
        ], [
            'Affectation' => 'App\\Entity\\Affectations',
        ]);
    }
}
