<?php

namespace ContainerWVTsjGy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_X7HcNWyService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.X7HcNWy' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.X7HcNWy'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'typeDocumentsRepository' => ['privates', 'App\\Repository\\TypeDocumentsRepository', 'getTypeDocumentsRepositoryService', true],
        ], [
            'typeDocumentsRepository' => 'App\\Repository\\TypeDocumentsRepository',
        ]);
    }
}
