<?php

namespace ContainerWVTsjGy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QKztdNgService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qKztdNg' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qKztdNg'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'secretariat' => ['privates', '.errored..service_locator.qKztdNg.App\\Entity\\Secretariats', NULL, 'Cannot autowire service ".service_locator.qKztdNg": it needs an instance of "App\\Entity\\Secretariats" but this type has been excluded in "config/services.yaml".'],
        ], [
            'secretariat' => 'App\\Entity\\Secretariats',
        ]);
    }
}
