<?php

namespace ContainerWVTsjGy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_3eWdoyBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.3eWdoyB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.3eWdoyB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'direction' => ['privates', '.errored..service_locator.3eWdoyB.App\\Entity\\Directions', NULL, 'Cannot autowire service ".service_locator.3eWdoyB": it needs an instance of "App\\Entity\\Directions" but this type has been excluded in "config/services.yaml".'],
            'directionsRepository' => ['privates', 'App\\Repository\\DirectionsRepository', 'getDirectionsRepositoryService', true],
            'divisionsRepository' => ['privates', 'App\\Repository\\DivisionsRepository', 'getDivisionsRepositoryService', true],
            'servicesRepository' => ['privates', 'App\\Repository\\ServicesRepository', 'getServicesRepositoryService', true],
        ], [
            'direction' => 'App\\Entity\\Directions',
            'directionsRepository' => 'App\\Repository\\DirectionsRepository',
            'divisionsRepository' => 'App\\Repository\\DivisionsRepository',
            'servicesRepository' => 'App\\Repository\\ServicesRepository',
        ]);
    }
}
