<?php

namespace ContainerWVTsjGy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_E6uZs1YService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.e6uZs1Y' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.e6uZs1Y'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'divisionsRepository' => ['privates', 'App\\Repository\\DivisionsRepository', 'getDivisionsRepositoryService', true],
            'postesRepository' => ['privates', 'App\\Repository\\PostesRepository', 'getPostesRepositoryService', true],
            'usersRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'divisionsRepository' => 'App\\Repository\\DivisionsRepository',
            'postesRepository' => 'App\\Repository\\PostesRepository',
            'usersRepository' => 'App\\Repository\\UsersRepository',
        ]);
    }
}
