<?php

namespace ContainerWVTsjGy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Scp2ZthService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.Scp2Zth' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.Scp2Zth'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'directionsRepository' => ['privates', 'App\\Repository\\DirectionsRepository', 'getDirectionsRepositoryService', true],
            'divisionsRepository' => ['privates', 'App\\Repository\\DivisionsRepository', 'getDivisionsRepositoryService', true],
            'hash' => ['privates', 'security.user_password_hasher', 'getSecurity_UserPasswordHasherService', true],
            'request' => ['privates', '.errored.ylKNKYh', NULL, 'Cannot determine controller argument for "App\\Controller\\InitialisedDataController::index()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?'],
            'servicesRepository' => ['privates', 'App\\Repository\\ServicesRepository', 'getServicesRepositoryService', true],
            'usersRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'directionsRepository' => 'App\\Repository\\DirectionsRepository',
            'divisionsRepository' => 'App\\Repository\\DivisionsRepository',
            'hash' => '?',
            'request' => '?',
            'servicesRepository' => 'App\\Repository\\ServicesRepository',
            'usersRepository' => 'App\\Repository\\UsersRepository',
        ]);
    }
}
