<?php

namespace ContainerWVTsjGy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4_TP9aJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4.tP9aJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4.tP9aJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'direction' => ['privates', '.errored..service_locator.4.tP9aJ.App\\Entity\\Directions', NULL, 'Cannot autowire service ".service_locator.4.tP9aJ": it needs an instance of "App\\Entity\\Directions" but this type has been excluded in "config/services.yaml".'],
            'directionsRepository' => ['privates', 'App\\Repository\\DirectionsRepository', 'getDirectionsRepositoryService', true],
        ], [
            'direction' => 'App\\Entity\\Directions',
            'directionsRepository' => 'App\\Repository\\DirectionsRepository',
        ]);
    }
}
