<?php

namespace ContainerWVTsjGy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_QrNQobService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.qr_NQob' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.qr_NQob'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'OldServices' => ['privates', '.errored..service_locator.qr_NQob.App\\Entity\\Services', NULL, 'Cannot autowire service ".service_locator.qr_NQob": it needs an instance of "App\\Entity\\Services" but this type has been excluded in "config/services.yaml".'],
            'postesRepository' => ['privates', 'App\\Repository\\PostesRepository', 'getPostesRepositoryService', true],
            'service' => ['privates', '.errored..service_locator.qr_NQob.App\\Entity\\Services', NULL, 'Cannot autowire service ".service_locator.qr_NQob": it needs an instance of "App\\Entity\\Services" but this type has been excluded in "config/services.yaml".'],
            'servicesRepository' => ['privates', 'App\\Repository\\ServicesRepository', 'getServicesRepositoryService', true],
        ], [
            'OldServices' => 'App\\Entity\\Services',
            'postesRepository' => 'App\\Repository\\PostesRepository',
            'service' => 'App\\Entity\\Services',
            'servicesRepository' => 'App\\Repository\\ServicesRepository',
        ]);
    }
}
