<?php

namespace ContainerWVTsjGy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator__TeuG0Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._.teuG0' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._.teuG0'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'document' => ['privates', '.errored..service_locator._.teuG0.App\\Entity\\Documents', NULL, 'Cannot autowire service ".service_locator._.teuG0": it needs an instance of "App\\Entity\\Documents" but this type has been excluded in "config/services.yaml".'],
            'documentsRepository' => ['privates', 'App\\Repository\\DocumentsRepository', 'getDocumentsRepositoryService', true],
            'provenancesRepository' => ['privates', 'App\\Repository\\ProvenancesRepository', 'getProvenancesRepositoryService', true],
        ], [
            'document' => 'App\\Entity\\Documents',
            'documentsRepository' => 'App\\Repository\\DocumentsRepository',
            'provenancesRepository' => 'App\\Repository\\ProvenancesRepository',
        ]);
    }
}
