<?php

namespace ContainerWVTsjGy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_HncW3MDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.hncW3MD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.hncW3MD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'user' => ['privates', '.errored..service_locator.hncW3MD.App\\Entity\\Users', NULL, 'Cannot autowire service ".service_locator.hncW3MD": it needs an instance of "App\\Entity\\Users" but this type has been excluded in "config/services.yaml".'],
            'usersRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'user' => 'App\\Entity\\Users',
            'usersRepository' => 'App\\Repository\\UsersRepository',
        ]);
    }
}
