<?php

namespace ContainerWVTsjGy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_RFWT_P4Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.rFWT.p4' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.rFWT.p4'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'poste' => ['privates', '.errored..service_locator.rFWT.p4.App\\Entity\\Postes', NULL, 'Cannot autowire service ".service_locator.rFWT.p4": it needs an instance of "App\\Entity\\Postes" but this type has been excluded in "config/services.yaml".'],
            'postesRepository' => ['privates', 'App\\Repository\\PostesRepository', 'getPostesRepositoryService', true],
        ], [
            'poste' => 'App\\Entity\\Postes',
            'postesRepository' => 'App\\Repository\\PostesRepository',
        ]);
    }
}
