<?php

namespace ContainerWVTsjGy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_G_ISFFGService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.G.iSFFG' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.G.iSFFG'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'User' => ['privates', '.errored..service_locator.G.iSFFG.App\\Entity\\Users', NULL, 'Cannot autowire service ".service_locator.G.iSFFG": it needs an instance of "App\\Entity\\Users" but this type has been excluded in "config/services.yaml".'],
            'directionsRepository' => ['privates', 'App\\Repository\\DirectionsRepository', 'getDirectionsRepositoryService', true],
            'divisionsRepository' => ['privates', 'App\\Repository\\DivisionsRepository', 'getDivisionsRepositoryService', true],
            'servicesRepository' => ['privates', 'App\\Repository\\ServicesRepository', 'getServicesRepositoryService', true],
            'usersRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'User' => 'App\\Entity\\Users',
            'directionsRepository' => 'App\\Repository\\DirectionsRepository',
            'divisionsRepository' => 'App\\Repository\\DivisionsRepository',
            'servicesRepository' => 'App\\Repository\\ServicesRepository',
            'usersRepository' => 'App\\Repository\\UsersRepository',
        ]);
    }
}
