<?php

namespace ContainerWVTsjGy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NE6aMb6Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NE6aMb6' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NE6aMb6'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'directionsRepository' => ['privates', 'App\\Repository\\DirectionsRepository', 'getDirectionsRepositoryService', true],
            'divisionsRepository' => ['privates', 'App\\Repository\\DivisionsRepository', 'getDivisionsRepositoryService', true],
            'document' => ['privates', '.errored..service_locator.NE6aMb6.App\\Entity\\Documents', NULL, 'Cannot autowire service ".service_locator.NE6aMb6": it needs an instance of "App\\Entity\\Documents" but this type has been excluded in "config/services.yaml".'],
            'documentsRepository' => ['privates', 'App\\Repository\\DocumentsRepository', 'getDocumentsRepositoryService', true],
            'postesRepository' => ['privates', 'App\\Repository\\PostesRepository', 'getPostesRepositoryService', true],
            'provenancesRepository' => ['privates', 'App\\Repository\\ProvenancesRepository', 'getProvenancesRepositoryService', true],
            'secretariatsController' => ['services', 'App\\Controller\\SecretariatsController', 'getSecretariatsControllerService', true],
            'secretariatsRepository' => ['privates', 'App\\Repository\\SecretariatsRepository', 'getSecretariatsRepositoryService', true],
            'servicesRepository' => ['privates', 'App\\Repository\\ServicesRepository', 'getServicesRepositoryService', true],
            'slugger' => ['privates', 'slugger', 'getSluggerService', true],
            'typeDocumentsRepository' => ['privates', 'App\\Repository\\TypeDocumentsRepository', 'getTypeDocumentsRepositoryService', true],
            'userRepository' => ['privates', 'App\\Repository\\UsersRepository', 'getUsersRepositoryService', true],
        ], [
            'directionsRepository' => 'App\\Repository\\DirectionsRepository',
            'divisionsRepository' => 'App\\Repository\\DivisionsRepository',
            'document' => 'App\\Entity\\Documents',
            'documentsRepository' => 'App\\Repository\\DocumentsRepository',
            'postesRepository' => 'App\\Repository\\PostesRepository',
            'provenancesRepository' => 'App\\Repository\\ProvenancesRepository',
            'secretariatsController' => 'App\\Controller\\SecretariatsController',
            'secretariatsRepository' => 'App\\Repository\\SecretariatsRepository',
            'servicesRepository' => 'App\\Repository\\ServicesRepository',
            'slugger' => '?',
            'typeDocumentsRepository' => 'App\\Repository\\TypeDocumentsRepository',
            'userRepository' => 'App\\Repository\\UsersRepository',
        ]);
    }
}
