<?php

namespace ContainerWVTsjGy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDirectionsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.3eWdoyB.App\Entity\Directions' shared service.
     *
     * @return \App\Entity\Directions
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.3eWdoyB": it needs an instance of "App\\Entity\\Directions" but this type has been excluded in "config/services.yaml".');
    }
}
