<?php

namespace ContainerWVTsjGy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getDivisions2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.nWoUxjQ.App\Entity\Divisions' shared service.
     *
     * @return \App\Entity\Divisions
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.nWoUxjQ": it needs an instance of "App\\Entity\\Divisions" but this type has been excluded in "config/services.yaml".');
    }
}
