<?php

namespace ContainerWVTsjGy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getSecretariatsTypeService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private 'App\Form\SecretariatsType' shared autowired service.
     *
     * @return \App\Form\SecretariatsType
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'FormTypeInterface.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'vendor'.\DIRECTORY_SEPARATOR.'symfony'.\DIRECTORY_SEPARATOR.'form'.\DIRECTORY_SEPARATOR.'AbstractType.php';
        include_once \dirname(__DIR__, 4).''.\DIRECTORY_SEPARATOR.'src'.\DIRECTORY_SEPARATOR.'Form'.\DIRECTORY_SEPARATOR.'SecretariatsType.php';

        $a = ($container->services['App\\Controller\\SecretariatsController'] ?? $container->load('getSecretariatsControllerService'));

        if (isset($container->privates['App\\Form\\SecretariatsType'])) {
            return $container->privates['App\\Form\\SecretariatsType'];
        }

        return $container->privates['App\\Form\\SecretariatsType'] = new \App\Form\SecretariatsType($a, ($container->privates['App\\Repository\\ServicesRepository'] ?? $container->load('getServicesRepositoryService')), ($container->privates['App\\Repository\\DivisionsRepository'] ?? $container->load('getDivisionsRepositoryService')));
    }
}
