<?php

namespace ContainerWVTsjGy;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getTypeDocuments2Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.f8PZTKM.App\Entity\TypeDocuments' shared service.
     *
     * @return \App\Entity\TypeDocuments
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.f8PZTKM": it needs an instance of "App\\Entity\\TypeDocuments" but this type has been excluded in "config/services.yaml".');
    }
}
